# Simple 2D Convolution using Images

In [31]:
import PIL
from PIL import Image
import numpy as np

alpha = 5
filterSize = 3

In [32]:
#import the photo
input = Image.open('input.jpeg')

In [33]:
#turn the photo into a pixel matrix
pixels = np.array(input)

In [34]:
#turn the image matrix into greyscale

cSize = (np.shape(pixels)[0])
#print (np.shape(pixels)[1])

greyscale = np.zeros((cSize,cSize), dtype = float)
for x in range(0, np.shape(pixels)[0]):
    for y in range(0, np.shape(pixels)[1]):
        greyscale[x,y] = pixels[x,y].sum() / 3
        
#print(greyscale)

In [35]:
#initialize the filter
filter = np.zeros((filterSize,filterSize), dtype = int)
filter[1][1] = alpha

In [44]:
#Pad the greyscale matrix with 0's
pSize = cSize + 2*(filterSize - 1)
padded = np.zeros((pSize,pSize), dtype = int)
#print(np.size(padded[0]))

x = filterSize - 1
y = filterSize - 1
padded[x:x+greyscale.shape[0], y:y+greyscale.shape[1]] = greyscale
#print(padded)

304
[[ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0 15 ... 42  0  0]
 ...
 [ 0  0 84 ... 90  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]]


In [22]:
#iterate through the matrix